# Generated by Django 5.2.5 on 2025-08-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='timestamp',
            new_name='changed_on',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='new_marks',
            new_name='new_score',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='old_marks',
            new_name='old_score',
        ),
        migrations.RenameField(
            model_name='sessiontoken',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='marks',
            new_name='score',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salt',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
