# Generated by Django 5.2.5 on 2025-08-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_timestamp_auditlog_changed_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='changed_on',
            new_name='changed_at',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='new_score',
            new_name='new_value',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='old_score',
            new_name='old_value',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='updated_by',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='sessiontoken',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='score',
            new_name='marks',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salt',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
